version: '3.8'
services:
  rag-backend-service:
    image: rag-backend:latest
    ports:
      - "8000:8000"
    env_file:
      - backend/.env

  rag-frontend:
    image: rag-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - rag-backend-service
